replicaCount: 2

image:
  repository: baram940/devops-test
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 30000
  targetPort: 3000
  nodePort: 30000  # 👈 반드시 추가

resources: {}
