name: Terraform Deploy or Destroy

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Terraform Action (apply or destroy)"
        required: true
        default: apply

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.terraform_action }}" = "destroy" ]; then
            terraform destroy -auto-approve -no-color
          else
            terraform apply -auto-approve -no-color
          fi
